from __future__ import annotations

from .flywheel import LabeledFlywheelInput


BASIC_FLYWHEEL_SAMPLES: list[LabeledFlywheelInput] = [
    LabeledFlywheelInput("今天先做什么", "today"),
    LabeledFlywheelInput("今天最紧急的是什么", "today"),
    LabeledFlywheelInput("show today's list", "today"),
    LabeledFlywheelInput("what should I do first", "today"),
    LabeledFlywheelInput("哪些待处理", "today"),
    LabeledFlywheelInput("我现在应该先处理什么", "today"),
    LabeledFlywheelInput("今天有啥要办", "today"),
    LabeledFlywheelInput("give me my todo list", "today"),
    LabeledFlywheelInput("priority for today", "today"),
    LabeledFlywheelInput("list urgent items", "today"),
    LabeledFlywheelInput("今天的优先级", "today"),
    LabeledFlywheelInput("今天还有什么没处理", "today"),
    LabeledFlywheelInput("what is due today", "today"),
    LabeledFlywheelInput("今天到期的有哪些", "today"),
    LabeledFlywheelInput("先给我今天的工作", "today"),
    LabeledFlywheelInput("today queue", "today"),
    LabeledFlywheelInput("show urgent work", "today"),
    LabeledFlywheelInput("我今天需要盯什么", "today"),
    LabeledFlywheelInput("今天的任务清单", "today"),
    LabeledFlywheelInput("今天最该做哪个", "today"),
    LabeledFlywheelInput("先看 Acme", "client_deadline_list"),
    LabeledFlywheelInput("打开 Acme LLC", "client_deadline_list"),
    LabeledFlywheelInput("查看 Acme", "client_deadline_list"),
    LabeledFlywheelInput("open Acme", "client_deadline_list"),
    LabeledFlywheelInput("show me Acme", "client_deadline_list"),
    LabeledFlywheelInput("Acme 今天有什么", "client_deadline_list"),
    LabeledFlywheelInput("Acme 的截止日", "client_deadline_list"),
    LabeledFlywheelInput("先看今天最急的 Acme", "client_deadline_list"),
    LabeledFlywheelInput("focus on Acme", "client_deadline_list"),
    LabeledFlywheelInput("Acme Dental", "client_deadline_list"),
    LabeledFlywheelInput("帮我看看 Acme", "client_deadline_list"),
    LabeledFlywheelInput("Acme 现在卡在哪里", "client_deadline_list"),
    LabeledFlywheelInput("先别标记完成，给我看 Acme", "client_deadline_list"),
    LabeledFlywheelInput("帮我处理 Acme 但先别标记完成", "client_deadline_list"),
    LabeledFlywheelInput("Acme 这个客户怎么了", "client_deadline_list"),
    LabeledFlywheelInput("Acme 有哪些 pending", "client_deadline_list"),
    LabeledFlywheelInput("pull up Acme", "client_deadline_list"),
    LabeledFlywheelInput("Acme status", "client_deadline_list"),
    LabeledFlywheelInput("看一下 Acme 的 sales tax", "client_deadline_list"),
    LabeledFlywheelInput("Acme 卡住的那项", "client_deadline_list"),
    LabeledFlywheelInput("为什么这个还没完成", "deadline_history"),
    LabeledFlywheelInput("这个为什么变了", "deadline_history"),
    LabeledFlywheelInput("show history", "deadline_history"),
    LabeledFlywheelInput("what changed", "deadline_history"),
    LabeledFlywheelInput("看看当前这个的历史", "deadline_history"),
    LabeledFlywheelInput("这个来源是什么", "deadline_history"),
    LabeledFlywheelInput("why is this blocked", "deadline_history"),
    LabeledFlywheelInput("who changed this", "deadline_history"),
    LabeledFlywheelInput("这条记录怎么来的", "deadline_history"),
    LabeledFlywheelInput("source for this item", "deadline_history"),
    LabeledFlywheelInput("why did the due date move", "deadline_history"),
    LabeledFlywheelInput("看一下变更记录", "deadline_history"),
    LabeledFlywheelInput("audit trail for this", "deadline_history"),
    LabeledFlywheelInput("这个状态为什么是 blocked", "deadline_history"),
    LabeledFlywheelInput("完成第一条", "deadline_action_complete"),
    LabeledFlywheelInput("mark first done", "deadline_action_complete"),
    LabeledFlywheelInput("mark as sent", "deadline_action_complete"),
    LabeledFlywheelInput("把这个记为已处理", "deadline_action_complete"),
    LabeledFlywheelInput("处理掉当前这个", "deadline_action_complete"),
    LabeledFlywheelInput("这个已经完成了", "deadline_action_complete"),
    LabeledFlywheelInput("mark current complete", "deadline_action_complete"),
    LabeledFlywheelInput("record it as done", "deadline_action_complete"),
    LabeledFlywheelInput("已发送，记录一下", "deadline_action_complete"),
    LabeledFlywheelInput("可以标记完成", "deadline_action_complete"),
    LabeledFlywheelInput("mark it complete", "deadline_action_complete"),
    LabeledFlywheelInput("record this as handled", "deadline_action_complete"),
    LabeledFlywheelInput("这个已经办完了", "deadline_action_complete"),
    LabeledFlywheelInput("set this to complete", "deadline_action_complete"),
    LabeledFlywheelInput("client sent it, mark done", "deadline_action_complete"),
    LabeledFlywheelInput("暂时不做", "defer"),
    LabeledFlywheelInput("先不做这个", "defer"),
    LabeledFlywheelInput("先别动", "defer"),
    LabeledFlywheelInput("later", "defer"),
    LabeledFlywheelInput("not now", "defer"),
    LabeledFlywheelInput("skip for now", "defer"),
    LabeledFlywheelInput("这个先放一下", "defer"),
    LabeledFlywheelInput("don't mark complete", "defer"),
    LabeledFlywheelInput("先等等", "defer"),
    LabeledFlywheelInput("leave it for now", "defer"),
    LabeledFlywheelInput("不要处理这个", "defer"),
    LabeledFlywheelInput("hold off on this", "defer"),
    LabeledFlywheelInput("help", "help"),
    LabeledFlywheelInput("怎么用", "help"),
    LabeledFlywheelInput("你能干嘛", "help"),
    LabeledFlywheelInput("what can you do", "help"),
    LabeledFlywheelInput("help me understand commands", "help"),
    LabeledFlywheelInput("这个系统怎么用", "help"),
    LabeledFlywheelInput("你支持哪些操作", "help"),
    LabeledFlywheelInput("show help", "help"),
    LabeledFlywheelInput("未来30天有什么", "upcoming_deadlines"),
    LabeledFlywheelInput("下个月忙不忙", "upcoming_deadlines"),
    LabeledFlywheelInput("next month deadlines", "upcoming_deadlines"),
    LabeledFlywheelInput("upcoming deadlines", "upcoming_deadlines"),
    LabeledFlywheelInput("what is coming due", "upcoming_deadlines"),
    LabeledFlywheelInput("接下来有哪些截止日", "upcoming_deadlines"),
    LabeledFlywheelInput("未来一个月的任务", "upcoming_deadlines"),
    LabeledFlywheelInput("show next 30 days", "upcoming_deadlines"),
    LabeledFlywheelInput("30 days due list", "upcoming_deadlines"),
    LabeledFlywheelInput("下个月要处理什么", "upcoming_deadlines"),
    LabeledFlywheelInput("已完成的有哪些", "completed_deadlines"),
    LabeledFlywheelInput("show completed", "completed_deadlines"),
    LabeledFlywheelInput("completed deadlines", "completed_deadlines"),
    LabeledFlywheelInput("done items", "completed_deadlines"),
    LabeledFlywheelInput("完成记录", "completed_deadlines"),
    LabeledFlywheelInput("what has been handled", "completed_deadlines"),
    LabeledFlywheelInput("看看已经处理的", "completed_deadlines"),
    LabeledFlywheelInput("finished work", "completed_deadlines"),
    LabeledFlywheelInput("通知预览", "notification_preview"),
    LabeledFlywheelInput("提醒有哪些", "notification_preview"),
    LabeledFlywheelInput("show reminders", "notification_preview"),
    LabeledFlywheelInput("notification preview", "notification_preview"),
    LabeledFlywheelInput("要发哪些邮件", "notification_preview"),
    LabeledFlywheelInput("email preview", "notification_preview"),
    LabeledFlywheelInput("接下来要催谁", "notification_preview"),
    LabeledFlywheelInput("notify preview", "notification_preview"),
    LabeledFlywheelInput("规则审核队列", "rule_review"),
    LabeledFlywheelInput("低置信规则", "rule_review"),
    LabeledFlywheelInput("rule review queue", "rule_review"),
    LabeledFlywheelInput("pending review rules", "rule_review"),
    LabeledFlywheelInput("low confidence rules", "rule_review"),
    LabeledFlywheelInput("有哪些规则要审核", "rule_review"),
    LabeledFlywheelInput("show review queue", "rule_review"),
    LabeledFlywheelInput("rule parsing issues", "rule_review"),
    LabeledFlywheelInput("客户列表", "client_list"),
    LabeledFlywheelInput("所有客户", "client_list"),
    LabeledFlywheelInput("有哪些客户", "client_list"),
    LabeledFlywheelInput("client list", "client_list"),
    LabeledFlywheelInput("all clients", "client_list"),
    LabeledFlywheelInput("show clients", "client_list"),
    LabeledFlywheelInput("list clients", "client_list"),
    LabeledFlywheelInput("把客户都列出来", "client_list"),
]


BASIC_FLYWHEEL_SAMPLES.extend(
    [
        LabeledFlywheelInput("show my work queue", "today"),
        LabeledFlywheelInput("top priority right now", "today"),
        LabeledFlywheelInput("morning list", "today"),
        LabeledFlywheelInput("what is due today", "today"),
        LabeledFlywheelInput("deadline today", "today"),
        LabeledFlywheelInput("今天 deadline", "today"),
        LabeledFlywheelInput("今天哪些比较急", "today"),
        LabeledFlywheelInput("现在最该盯哪个", "today"),
        LabeledFlywheelInput("先给我最急的", "today"),
        LabeledFlywheelInput("today top priority", "today"),
        LabeledFlywheelInput("Acme deadline", "client_deadline_list"),
        LabeledFlywheelInput("Acme pending deadlines", "client_deadline_list"),
        LabeledFlywheelInput("Acme work", "client_deadline_list"),
        LabeledFlywheelInput("where is Acme stuck", "client_deadline_list"),
        LabeledFlywheelInput("look at Acme first", "client_deadline_list"),
        LabeledFlywheelInput("open the Acme item", "client_deadline_list"),
        LabeledFlywheelInput("show Acme status", "client_deadline_list"),
        LabeledFlywheelInput("Acme client status", "client_deadline_list"),
        LabeledFlywheelInput("Acme sales tax item", "client_deadline_list"),
        LabeledFlywheelInput("不要处理 Acme，先给我看一下", "client_deadline_list"),
        LabeledFlywheelInput("audit for this item", "deadline_history"),
        LabeledFlywheelInput("audit trail", "deadline_history"),
        LabeledFlywheelInput("who touched this item", "deadline_history"),
        LabeledFlywheelInput("why blocked", "deadline_history"),
        LabeledFlywheelInput("why did this get blocked", "deadline_history"),
        LabeledFlywheelInput("这个是谁改的", "deadline_history"),
        LabeledFlywheelInput("这个截止日为什么变了", "deadline_history"),
        LabeledFlywheelInput("当前这个的 audit", "deadline_history"),
        LabeledFlywheelInput("show the source", "deadline_history"),
        LabeledFlywheelInput("为什么会是这个日期", "deadline_history"),
        LabeledFlywheelInput("close this", "deadline_action_complete"),
        LabeledFlywheelInput("resolve this", "deadline_action_complete"),
        LabeledFlywheelInput("sent to client", "deadline_action_complete"),
        LabeledFlywheelInput("client replied, mark it done", "deadline_action_complete"),
        LabeledFlywheelInput("mark this as handled", "deadline_action_complete"),
        LabeledFlywheelInput("这个可以关掉了", "deadline_action_complete"),
        LabeledFlywheelInput("把当前项关掉", "deadline_action_complete"),
        LabeledFlywheelInput("这个已经发给客户了", "deadline_action_complete"),
        LabeledFlywheelInput("record current item as complete", "deadline_action_complete"),
        LabeledFlywheelInput("finish this item", "deadline_action_complete"),
        LabeledFlywheelInput("pause this", "defer"),
        LabeledFlywheelInput("hold off", "defer"),
        LabeledFlywheelInput("先放着", "defer"),
        LabeledFlywheelInput("先等等这个", "defer"),
        LabeledFlywheelInput("leave this alone for now", "defer"),
        LabeledFlywheelInput("do not complete this", "defer"),
        LabeledFlywheelInput("not complete this yet", "defer"),
        LabeledFlywheelInput("暂时不要处理", "defer"),
        LabeledFlywheelInput("先不要标记", "defer"),
        LabeledFlywheelInput("稍后再说", "defer"),
        LabeledFlywheelInput("what can you do for me", "help"),
        LabeledFlywheelInput("show available operations", "help"),
        LabeledFlywheelInput("你能做什么", "help"),
        LabeledFlywheelInput("支持哪些操作", "help"),
        LabeledFlywheelInput("有哪些命令", "help"),
        LabeledFlywheelInput("command help", "help"),
        LabeledFlywheelInput("help with due date hq", "help"),
        LabeledFlywheelInput("这个助手能干嘛", "help"),
        LabeledFlywheelInput("next week deadlines", "upcoming_deadlines"),
        LabeledFlywheelInput("this month due dates", "upcoming_deadlines"),
        LabeledFlywheelInput("month ahead", "upcoming_deadlines"),
        LabeledFlywheelInput("quarter ahead", "upcoming_deadlines"),
        LabeledFlywheelInput("coming due soon", "upcoming_deadlines"),
        LabeledFlywheelInput("接下来一周有什么", "upcoming_deadlines"),
        LabeledFlywheelInput("未来几周要做什么", "upcoming_deadlines"),
        LabeledFlywheelInput("下个月 deadline", "upcoming_deadlines"),
        LabeledFlywheelInput("show upcoming work", "upcoming_deadlines"),
        LabeledFlywheelInput("next 30 due dates", "upcoming_deadlines"),
        LabeledFlywheelInput("closed items", "completed_deadlines"),
        LabeledFlywheelInput("resolved items", "completed_deadlines"),
        LabeledFlywheelInput("what is already completed", "completed_deadlines"),
        LabeledFlywheelInput("show finished work", "completed_deadlines"),
        LabeledFlywheelInput("已经完成的任务", "completed_deadlines"),
        LabeledFlywheelInput("处理完成的列表", "completed_deadlines"),
        LabeledFlywheelInput("closed deadlines", "completed_deadlines"),
        LabeledFlywheelInput("handled work list", "completed_deadlines"),
        LabeledFlywheelInput("client reminders", "notification_preview"),
        LabeledFlywheelInput("send reminders", "notification_preview"),
        LabeledFlywheelInput("follow up emails", "notification_preview"),
        LabeledFlywheelInput("哪些客户要催", "notification_preview"),
        LabeledFlywheelInput("待发送提醒", "notification_preview"),
        LabeledFlywheelInput("提醒预览", "notification_preview"),
        LabeledFlywheelInput("show notification queue", "notification_preview"),
        LabeledFlywheelInput("who needs a reminder", "notification_preview"),
        LabeledFlywheelInput("source parsing issues", "rule_review"),
        LabeledFlywheelInput("rules needing review", "rule_review"),
        LabeledFlywheelInput("needs review rules", "rule_review"),
        LabeledFlywheelInput("show low confidence parsing", "rule_review"),
        LabeledFlywheelInput("规则解析问题", "rule_review"),
        LabeledFlywheelInput("哪些规则低置信", "rule_review"),
        LabeledFlywheelInput("pending rule review", "rule_review"),
        LabeledFlywheelInput("review parsed rules", "rule_review"),
        LabeledFlywheelInput("clients", "client_list"),
        LabeledFlywheelInput("client roster", "client_list"),
        LabeledFlywheelInput("show customer list", "client_list"),
        LabeledFlywheelInput("客户名录", "client_list"),
        LabeledFlywheelInput("全部客户", "client_list"),
        LabeledFlywheelInput("list customer accounts", "client_list"),
        LabeledFlywheelInput("show client roster", "client_list"),
    ]
)
