from __future__ import annotations

from typing import Protocol, Iterable

from .models import AuditRecord, Client, Deadline, Reminder, RuleVersion, Tenant


class TenantRepository(Protocol):
    def add(self, tenant: Tenant) -> None: ...
    def get(self, tenant_id: str) -> Tenant | None: ...
    def list(self) -> list[Tenant]: ...


class ClientRepository(Protocol):
    def add(self, client: Client) -> None: ...
    def get(self, tenant_id: str, client_id: str) -> Client | None: ...
    def list_by_tenant(self, tenant_id: str) -> list[Client]: ...


class RuleRepository(Protocol):
    def append(self, rule: RuleVersion) -> None: ...
    def list_versions(self) -> list[RuleVersion]: ...


class DeadlineRepository(Protocol):
    def add(self, deadline: Deadline) -> None: ...
    def get(self, tenant_id: str, deadline_id: str) -> Deadline | None: ...
    def list_by_tenant(self, tenant_id: str) -> list[Deadline]: ...


class ReminderRepository(Protocol):
    def add(self, reminder: Reminder) -> None: ...
    def list_by_tenant(self, tenant_id: str) -> list[Reminder]: ...


class AuditRepository(Protocol):
    def add(self, record: AuditRecord) -> None: ...
    def list_by_tenant(self, tenant_id: str) -> list[AuditRecord]: ...


class UnitOfWork(Protocol):
    def commit(self) -> None: ...
    def rollback(self) -> None: ...

